"""
Launcher generation for lsfg-vk.

Generates the ~/lsfg launch wrapper for each supported runtime.
"""

from .runtime import current_runtime


class LauncherGenerator:
    def __init__(self, service):
        self.service = service
        self.runtime = current_runtime()

    # ---------------------------------------------------------
    # Public API
    # ---------------------------------------------------------

    def generate(self, config) -> str:
        """
        Generate launcher from a configuration dictionary.
        """
        if self.runtime.native:
            return self._generate_arm(config)

        return self._generate_x86(config)

    def generate_profile(self, profile_data) -> str:
        """
        Generate launcher from profile data.
        """
        if self.runtime.native:
            return self._generate_arm_profile(profile_data)

        return self._generate_x86_profile(profile_data)

    # ---------------------------------------------------------
    # x86 launcher
    # ---------------------------------------------------------

    def _generate_x86(self, config) -> str:
        lines = [
            "#!/bin/bash",
            "",
            "# Generated by Decky LSFG-VK",
            "",
            "export LSFG_PROCESS=decky-lsfg-vk",
            "",
            'exec "$@"',
            "",
        ]

        return "\n".join(lines)

    def _generate_x86_profile(self, profile_data):
        profile = profile_data["current_profile"]

        lines = [
            "#!/bin/bash",
            "",
            "# Generated by Decky LSFG-VK",
            "",
            f"# Current profile: {profile}",
            "",
            f"export LSFG_PROCESS={profile}",
            "",
            'exec "$@"',
            "",
        ]

        return "\n".join(lines)

    # ---------------------------------------------------------
    # ARM64 launcher
    # ---------------------------------------------------------

    def _generate_arm(self, config):
        dll = config.get(
            "dll",
            "$HOME/.local/share/Steam/steamapps/common/Lossless Scaling/Lossless.dll",
        )

        lines = [
            "#!/bin/bash",
            "",
            "# Generated by Decky LSFG-VK (Armada)",
            "",
            "export LSFG_ENABLE=1",
            "export LSFGVK_ENV=1",
            f'export LSFGVK_DLL_PATH="{dll}"',
            'export STEAM_COMPAT_FEX_CONFIG="$HOME/.config/fex-emu/Config.json"',
            "",
            'exec "$@"',
            "",
        ]

        return "\n".join(lines)

    def _generate_arm_profile(self, profile_data):
        profile_name = profile_data["current_profile"]
        profile = profile_data["profiles"][profile_name]

        dll = profile_data.get("global_config", {}).get(
            "dll",
            "$HOME/.local/share/Steam/steamapps/common/Lossless Scaling/Lossless.dll",
        )

        multiplier = profile.get("multiplier", 2)
        fps_limit = profile.get("fps_limit", 30)
        flow_scale = profile.get("flow_scale", 0.3)
        performance_mode = profile.get("performance_mode", 1)

        lines = [
            "#!/bin/bash",
            "",
            "# Generated by Decky LSFG-VK (Armada)",
            "",
            f"# Current profile: {profile_name}",
            "",
            "export LSFG_ENABLE=1",
            "export LSFGVK_ENV=1",
            f'export LSFGVK_DLL_PATH="{dll}"',
            f"export LSFGVK_MULTIPLIER={multiplier}",
            f"export LSFGVK_FLOW_SCALE={flow_scale}",
            f"export LSFGVK_PERFORMANCE_MODE={performance_mode}",
            f"export DXVK_FRAME_RATE={fps_limit}",
            'export STEAM_COMPAT_FEX_CONFIG="$HOME/.config/fex-emu/Config.json"',
            "",
            'exec "$@"',
            "",
        ]

        return "\n".join(lines)
